### ISSUE TITLE
Link for project Portfolio with Media Query.

### ISSUE THREAD

**Issue by digia3d** [digia3d/First-Portfolio#10]
https://digia3d.github.io/Portfolio/
This is my Portfolio. Any suggestion, advice and comment is welcome.

**Comment by Lameck1** [comment]
Hi, @digia3d,

Tasks for this project have been successfully implemented 💯.

## Highlights
- Professional README ✔️
- Clean code ✔️ 
- Good commit messages ✔️ 

All the best with the next project.

You are free to merge this branch :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**Please, remember to tag me in your question so I can receive the notification.**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by digia3d** [comment]
Thank's for quick and nice review.
